import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Cairo } from "next/font/google";
import NavBar from "@/app/sharedcomponent/nav-bar";
import Footer from "@/app/sharedcomponent/footer";
import DarkMode from "@/app/utils/dark-mode";

const cairo = Cairo({
  subsets: ["arabic"],
  weights: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <DarkMode>
          <NavBar />
          {children}
          <Footer />
        </DarkMode>
      </body>
    </html>
  );
}
